.TH "chkconc" 1 "2003 Dec 20" "Debian" "canna"
.SH NAME
chkconc \- list concatenation for hinshi
.SH SYNOPSIS
.BI "chkconc [" "options" "] " "hinshi"
.SH DESCRIPTION
Displays possible 
.I hinshi
connections.
.SH OPTIONS
.BI "-d [" "dictionary path" "]"

specify the path to dictionary file.


.SH AUTHOR
This manual page was written by Junichi Uekawa 
(dancer@debian.org) for Debian GNU/Linux and may be used by others.
