#! /bin/sh
#
# This file was automatically customized by debmake on Thu, 14 Nov 1996 01:44:07 +0900
#
# Written by Miquel van Smoorenburg <miquels@drinkel.ow.org>.
# Modified for Debian GNU/Linux by Ian Murdock <imurdock@gnu.ai.mit.edu>.
# Modified for Debian by Christoph Lameter <clameter@debian.org>

### BEGIN INIT INFO
# Provides:          canna
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: canna Japanese Input System
# Description:       Canna provides a unified user interface for inputting Japanese.
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
CANNASERVER=/usr/sbin/cannaserver
CANNAKILL=/usr/bin/cannakill
CANNASTAT=/usr/bin/cannastat
CANNA_SERVER_OPT="-u canna"

if [ -e /etc/default/canna ] ; then
    . /etc/default/canna
fi

# The following value is extracted by debstd to figure out how to generate
# the postinst script. Edit the field to change the way the script is
# registered through update-rc.d (see the manpage for update-rc.d!)
FLAGS="defaults 98"

test -f $CANNASERVER || exit 0
test -f $CANNAKILL || exit 0
[ "${CANNA_SERVER_RUN}" = "no" ] && exit 0
if [ "${CANNA_ENABLE_INET}" = "yes" ] ; then
    CANNA_INET_OPT="-inet"
else
    CANNA_INET_OPT=""
fi

. /lib/lsb/init-functions

RUN_SERVER=1

case "$1" in
  start)
    echo "Starting cannaserver..."
    $CANNASERVER $CANNA_INET_OPT $CANNA_SERVER_OPT
    ;;
  stop)
    echo "Stopping cannaserver..."
    $CANNAKILL
    ;;
  force-reload|restart)
    echo "Restarting cannaserver..."
    $CANNAKILL
    $CANNASERVER $CANNA_INET_OPT $CANNA_SERVER_OPT
    ;;
  status)
    $CANNASTAT
    ;;
  *)
    echo "Usage: /etc/init.d/$0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
