#!/bin/sh

# Source debconf library.
. /usr/share/debconf/confmodule
db_version 2.0

case "$1" in
    configure)
    if [ ! -f /etc/canna/default.canna ] ; then
	db_get canna/default_style
	cp /usr/share/canna/${RET}.canna /etc/canna/default.canna
    fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

ldconfig

#DEBHELPER#
