#!/bin/sh -e

chown bin.bin /var/lib/canna/dic/canna
chown bin.bin /var/lib/canna/dic/canna/fuzokugo.cbd
chown bin.bin /var/lib/canna/dic/canna/fuzokugo.cld
chown bin.bin /var/lib/canna/dic/canna/iroha.cbd
chown bin.bin /var/lib/canna/dic/canna/iroha.cld
chown bin.bin /var/lib/canna/dic/canna/bushu.cld
chown bin.bin /var/log/canna/

chmod 775 /var/lib/canna/dic/canna
chmod 775 /var/log/canna/
chmod 664 /var/lib/canna/dic/canna/fuzokugo.cbd
chmod 664 /var/lib/canna/dic/canna/fuzokugo.cld
chmod 664 /var/lib/canna/dic/canna/iroha.cbd
chmod 664 /var/lib/canna/dic/canna/iroha.cld
chmod 664 /var/lib/canna/dic/canna/bushu.cld

#DEBHELPER#
