#!/bin/sh

case "$1" in
    configure)
    adduser --quiet --system --group --no-create-home  --home /var/lib/canna --gecos "Canna server" --disabled-password --disabled-login canna
    chown -R canna.canna /var/lib/canna
    chown -R canna.canna /var/log/canna
    /usr/sbin/update-canna-dics_dir
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#
exit 0
