
// Escape internal symbols.

#define AlphaMode                           G001_AlphaMode
#define BackspaceBehavesAsQuit              G002_BackspaceBehavesAsQuit
#define CannaBeep                           G003_CannaBeep
#define BreakIntoRoman                      G004_BreakIntoRoman
#define BunsetsuKugiri                      G005_BunsetsuKugiri
#define BushuMode                           G006_BushuMode
#define CANNA_initfilename                  G007_CANNA_initfilename
#define CNvW2E                              G008_CNvW2E
#define CYsearchfunc                        G009_CYsearchfunc
#define CannaVersion                        G010_CannaVersion
#define ChBasedMove                         G011_ChBasedMove
#define ChikujiContinue                     G012_ChikujiContinue
#define ChikujiSubstYomi                    G013_ChikujiSubstYomi
#define ChikujiTanDeletePrevious            G014_ChikujiTanDeletePrevious
#define ConvertAsBushu                      G015_ConvertAsBushu
#define CursorWrap                          G016_CursorWrap
#define DoFuncSequence                      G017_DoFuncSequence
#define EUCListCallback                     G018_EUCListCallback
#define EmptyBaseEisu                       G019_EmptyBaseEisu
#define EmptyBaseHan                        G020_EmptyBaseHan
#define EmptyBaseHenkan                     G021_EmptyBaseHenkan
#define EmptyBaseHira                       G022_EmptyBaseHira
#define EmptyBaseKakutei                    G023_EmptyBaseKakutei
#define EmptyBaseKana                       G024_EmptyBaseKana
#define EmptyBaseKata                       G025_EmptyBaseKata
#define EmptyBaseModeInfo                   G026_EmptyBaseModeInfo
#define EmptyBaseZen                        G027_EmptyBaseZen
#define EnglishTable                        G028_EnglishTable
#define FindExtraFunc                       G029_FindExtraFunc
#define GLineNGReturn                       G030_GLineNGReturn
#define GLineNGReturnFI                     G031_GLineNGReturnFI
#define GLineNGReturnTK                     G032_GLineNGReturnTK
#define Gakushu                             G033_Gakushu
#define GetKanjiString                      G034_GetKanjiString
#define GlineClear                          G035_GlineClear
#define HenkanNyuryokuMode                  G036_HenkanNyuryokuMode
#define HexMode                             G037_HexMode
#define HexkeySelect                        G038_HexkeySelect
#define HiraganaGakushu                     G039_HiraganaGakushu
#define IchiranBackwardKouho                G040_IchiranBackwardKouho
#define IchiranBeginningOfKouho             G041_IchiranBeginningOfKouho
#define IchiranEndOfKouho                   G042_IchiranEndOfKouho
#define IchiranForwardKouho                 G043_IchiranForwardKouho
#define IchiranNextKouhoretsu               G044_IchiranNextKouhoretsu
#define IchiranNop                          G045_IchiranNop
#define IchiranPreviousKouhoretsu           G046_IchiranPreviousKouhoretsu
#define IchiranQuit                         G047_IchiranQuit
#define InhibitHankakuKana                  G048_InhibitHankakuKana
#define JapaneseMode                        G049_JapaneseMode
#define KanaDeletePrevious                  G050_KanaDeletePrevious
#define KanjiFin                            G051_KanjiFin
#define KanjiInit                           G052_KanjiInit
#define KatakanaGakushu                     G053_KatakanaGakushu
#define KeepCursorPosition                  G054_KeepCursorPosition
#define KigoIchiran                         G055_KigoIchiran
#define LearnNumericalType                  G056_LearnNumericalType
#define ModeNames                           G057_ModeNames
#define NoMoreMemory                        G058_NoMoreMemory
#define NothingChanged                      G059_NothingChanged
#define NothingChangedWithBeep              G060_NothingChangedWithBeep
#define NothingForGLine                     G061_NothingForGLine
#define NothingForGLineWithBeep             G062_NothingForGLineWithBeep
#define QuitIchiranIfEnd                    G063_QuitIchiranIfEnd
#define RenbunContinue                      G064_RenbunContinue
#define RengoGakushu                        G065_RengoGakushu
#define ReverseWidely                       G066_ReverseWidely
#define ReverseWord                         G067_ReverseWord
#define RkGetServerHost                     G068_RkGetServerHost
#define RkSetServerName                     G069_RkSetServerName
#define rkc_config                          G070_rkc_config
#define rkc_configure                       G071_rkc_configure
#define rkc_config_fin                      G072_rkc_config_fin
#define rkc_errors                          G073_rkc_errors
#define RkcErrorBuf_get                     G074_RkcErrorBuf_get
#define RkcConfMgr_get_string               G075_RkcConfMgr_get_string
#define RkcConfMgr_get_number               G076_RkcConfMgr_get_number
#define RkcConfMgr_get_yesno                G077_RkcConfMgr_get_yesno
#define RomajiClearYomi                     G078_RomajiClearYomi
#define RomajiFlushYomi                     G079_RomajiFlushYomi
#define RomajiStoreYomi                     G080_RomajiStoreYomi
#define RomkanaFin                          G081_RomkanaFin
#define RomkanaInit                         G082_RomkanaInit
#define RomkanaTable                        G083_RomkanaTable
#define SelectDirect                        G084_SelectDirect
#define ServerFD                            G085_ServerFD
#define ServerTimeout                       G086_ServerTimeout
#define TanBackwardBunsetsu                 G087_TanBackwardBunsetsu
#define TanBeginningOfBunsetsu              G088_TanBeginningOfBunsetsu
#define TanBubunKakutei                     G089_TanBubunKakutei
#define TanBubunMuhenkan                    G090_TanBubunMuhenkan
#define TanCapitalize                       G091_TanCapitalize
#define TanDeletePrevious                   G092_TanDeletePrevious
#define TanEndOfBunsetsu                    G093_TanEndOfBunsetsu
#define TanForwardBunsetsu                  G094_TanForwardBunsetsu
#define TanHankaku                          G095_TanHankaku
#define TanHiragana                         G096_TanHiragana
#define TanKakutei                          G097_TanKakutei
#define TanKatakana                         G098_TanKatakana
#define TanKouhoIchiran                     G099_TanKouhoIchiran
#define TanMuhenkan                         G100_TanMuhenkan
#define TanNextKouho                        G101_TanNextKouho
#define TanNop                              G102_TanNop
#define TanPreviousKouho                    G103_TanPreviousKouho
#define TanPrintBunpou                      G104_TanPrintBunpou
#define TanRomaji                           G105_TanRomaji
#define TanUpper                            G106_TanUpper
#define TanZenkaku                          G107_TanZenkaku
#define TbBackward                          G108_TbBackward
#define TbBeginningOfLine                   G109_TbBeginningOfLine
#define TbEndOfLine                         G110_TbEndOfLine
#define TbForward                           G111_TbForward
#define ToggleChikuji                       G112_ToggleChikuji
#define UiUtilMode                          G113_UiUtilMode
#define UseOtherKeymap                      G114_UseOtherKeymap
#define WCinit                              G115_WCinit
#define WIsG0                               G116_WIsG0
#define WIsG1                               G117_WIsG1
#define WIsG2                               G118_WIsG2
#define WIsG3                               G119_WIsG3
#define WSfree                              G120_WSfree
#define WStraddbcpy                         G121_WStraddbcpy
#define WStrcat                             G122_WStrcat
#define WStrcmp                             G123_WStrcmp
#define WStrcpy                             G124_WStrcpy
#define WString                             G125_WString
#define WStringClose                        G126_WStringClose
#define WStringOpen                         G127_WStringOpen
#define WStrlen                             G128_WStrlen
#define WStrncmp                            G129_WStrncmp
#define WStrncpy                            G130_WStrncpy
#define WToupper                            G131_WToupper
#define WWhatGPlain                         G132_WWhatGPlain
#define YYparse_by_rcfilename               G133_YYparse_by_rcfilename
#define YomiBaseHiraKataToggle              G134_YomiBaseHiraKataToggle
#define YomiBaseKakuteiHenkanToggle         G135_YomiBaseKakuteiHenkanToggle
#define YomiBaseKanaEisuToggle              G136_YomiBaseKanaEisuToggle
#define YomiBaseRotateBack                  G137_YomiBaseRotateBack
#define YomiBaseRotateForw                  G138_YomiBaseRotateForw
#define YomiBaseZenHanToggle                G139_YomiBaseZenHanToggle
#define YomiExit                            G140_YomiExit
#define YomiInsert                          G141_YomiInsert
#define YomiKakutei                         G142_YomiKakutei
#define YomiMark                            G143_YomiMark
#define YomiModeBackup                      G144_YomiModeBackup
#define YomiQuotedInsert                    G145_YomiQuotedInsert
#define Yomisearchfunc                      G146_Yomisearchfunc
#define _RkwGetYomi                         G147__RkwGetYomi
#define _afterDoFunc                        G148__afterDoFunc
#define _doFunc                             G149__doFunc
#define _do_func_slightly                   G150__do_func_slightly
#define abandonContext                      G151_abandonContext
#define abandonIllegalPhono                 G152_abandonIllegalPhono
#define actFromHash                         G153_actFromHash
#define addWarningMesg                      G154_addWarningMesg
#define allocIchiranBuf                     G155_allocIchiranBuf
#define allocMenu                           G156_allocMenu
#define allowNextInput                      G157_allowNextInput
#define alphaMode                           G158_alphaMode
#define alpha_kmap                          G159_alpha_kmap
#define alpha_mode                          G160_alpha_mode
#define alphamap                            G161_alphamap
#define appendTan2Yomi                      G162_appendTan2Yomi
#define askQuitKey                          G163_askQuitKey
#define auto_define                         G164_auto_define
#define auto_sync                           G165_auto_sync
#define bunsetsu_mode                       G166_bunsetsu_mode
#define canna_alert                         G167_canna_alert
#define cb_mode                             G168_cb_mode
#define changeKeyfunc                       G169_changeKeyfunc
#define changeKeyfuncOfAll                  G170_changeKeyfuncOfAll
#define changeModeName                      G171_changeModeName
#define checkGLineLen                       G172_checkGLineLen
#define chikuji                             G173_chikuji
#define chikujiInit                         G174_chikujiInit
#define chikujiRealBackspace                G175_chikujiRealBackspace
#define chikuji_debug                       G176_chikuji_debug
#define ckverbose                           G177_ckverbose
#define clearHenkanContext                  G178_clearHenkanContext
#define clearYomi                           G179_clearYomi
#define clearYomiContext                    G180_clearYomiContext
#define clisp_fin                           G181_clisp_fin
#define clisp_init                          G182_clisp_init
#define clisp_main                          G183_clisp_main
#define code_input                          G184_code_input
#define confirmContext                      G185_confirmContext
#define containUnconvertedKey               G186_containUnconvertedKey
#define context_table                       G187_context_table
#define convertAsHex                        G188_convertAsHex
#define copyS8                              G189_copyS8
#define currentModeInfo                     G190_currentModeInfo
#define cutOffLeftSide                      G191_cutOffLeftSide
#define cvtAsHex                            G192_cvtAsHex
#define cy_mode                             G193_cy_mode
#define defaultBushuContext                 G194_defaultBushuContext
#define defaultContext                      G195_defaultContext
#define default_kmap                        G196_default_kmap
#define dicMount                            G197_dicMount
#define dicSakujo                           G198_dicSakujo
#define dicTouroku                          G199_dicTouroku
#define dicTourokuControl                   G200_dicTourokuControl
#define dicTourokuDictionary                G201_dicTourokuDictionary
#define dicTourokuHinshi                    G202_dicTourokuHinshi
#define dicTourokuHinshiDelivery            G203_dicTourokuHinshiDelivery
#define dicTourokuTango                     G204_dicTourokuTango
#define doFunc                              G205_doFunc
#define doHenkan                            G206_doHenkan
#define doHiraganaGakushu                   G207_doHiraganaGakushu
#define doKatakanaGakushu                   G208_doKatakanaGakushu
#define doMuhenkan                          G209_doMuhenkan
#define dupYomiContext                      G210_dupYomiContext
#define echostrClear                        G211_echostrClear
#define empty_kmap                          G212_empty_kmap
#define empty_mode                          G213_empty_mode
#define emptymap                            G214_emptymap
#define englishdic                          G215_englishdic
#define enterAdjustMode                     G216_enterAdjustMode
#define enterJishuMode                      G217_enterJishuMode
#define escapeToBasicStat                   G218_escapeToBasicStat
#define euc2ushort                          G219_euc2ushort
#define eucchars                            G220_eucchars
#define eucproto                            G221_eucproto
#define exitJishu                           G222_exitJishu
#define extractJishuString                  G223_extractJishuString
#define extractTanRomaji                    G224_extractTanRomaji
#define extractTanString                    G225_extractTanString
#define extractTanYomi                      G226_extractTanYomi
#define extrafuncp                          G227_extrafuncp
#define finExtMenu                          G228_finExtMenu
#define findExtraKanjiMode                  G229_findExtraKanjiMode
#define findSup                             G230_findSup
#define finishTanKakutei                    G231_finishTanKakutei
#define forceKana                           G232_forceKana
#define forceRomajiFlushYomi                G233_forceRomajiFlushYomi
#define freeAllMenuInfo                     G234_freeAllMenuInfo
#define freeAndPopTouroku                   G235_freeAndPopTouroku
#define freeDic                             G236_freeDic
#define freeGetIchiranList                  G237_freeGetIchiranList
#define freeIchiranBuf                      G238_freeIchiranBuf
#define freeMenu                            G239_freeMenu
#define freeRomeStruct                      G240_freeRomeStruct
#define freeTanContext                      G241_freeTanContext
#define generalReplace                      G242_generalReplace
#define getBaseMode                         G243_getBaseMode
#define getForIchiranContext                G244_getForIchiranContext
#define getIchiranList                      G245_getIchiranList
#define getMountContext                     G246_getMountContext
#define getTourokuContext                   G247_getTourokuContext
#define getUserDicName                      G248_getUserDicName
#define getYesNoContext                     G249_getYesNoContext
#define grammaticalQuestion                 G250_grammaticalQuestion
#define hexCharacterDefiningStyle           G251_hexCharacterDefiningStyle
#define hiraautodic                         G252_hiraautodic
#define howToBehaveInCaseOfUndefKey         G253_howToBehaveInCaseOfUndefKey
#define howToReturnModeInfo                 G254_howToReturnModeInfo
#define iListCB                             G255_iListCB
#define ichiranFin                          G256_ichiranFin
#define ichiran_mode                        G257_ichiran_mode
#define ignore_case                         G258_ignore_case
#define indexHankaku                        G259_indexHankaku
#define indexSeparator                      G260_indexSeparator
#define initBushuTable                      G261_initBushuTable
#define initExtMenu                         G262_initExtMenu
#define initFileSpecified                   G263_initFileSpecified
#define initGyouTable                       G264_initGyouTable
#define initHinshiMessage                   G265_initHinshiMessage
#define initHinshiTable                     G266_initHinshiTable
#define initIchiran                         G267_initIchiran
#define initKeyTables                       G268_initKeyTables
#define initKigoTable                       G269_initKigoTable
#define initModeNames                       G270_initModeNames
#define initOnoffTable                      G271_initOnoffTable
#define initRomeStruct                      G272_initRomeStruct
#define initUlKeisenTable                   G273_initUlKeisenTable
#define initUlKigoTable                     G274_initUlKigoTable
#define initfunc                            G275_initfunc
#define internContext                       G276_internContext
#define iroha_debug                         G277_iroha_debug
#define jishu_mode                          G278_jishu_mode
#define kCount                              G279_kCount
#define kPos2rPos                           G280_kPos2rPos
#define kakuteiIfEndOfBunsetsu              G281_kakuteiIfEndOfBunsetsu
#define kanjiControl                        G282_kanjiControl
#define kanjidicnames                       G283_kanjidicnames
#define kataautodic                         G284_kataautodic
#define keepCursorPosition                  G285_keepCursorPosition
#define key2wchar                           G286_key2wchar
#define keyToContext                        G287_keyToContext
#define keyconvCallback                     G288_keyconvCallback
#define keysup                              G289_keysup
#define kigoGreek                           G290_kigoGreek
#define kigoKeisen                          G291_kigoKeisen
#define kigoRussia                          G292_kigoRussia
#define kigo_mode                           G293_kigo_mode
#define kojin                               G294_kojin
#define kouho_threshold                     G295_kouho_threshold
#define leaveAdjustMode                     G296_leaveAdjustMode
#define leaveJishuMode                      G297_leaveJishuMode
#define makeAllContextToBeClosed            G298_makeAllContextToBeClosed
#define makeGLineMessage                    G299_makeGLineMessage
#define makeGLineMessageFromString          G300_makeGLineMessageFromString
#define makeGlineStatus                     G301_makeGlineStatus
#define makeKanjiStatusReturn               G302_makeKanjiStatusReturn
#define makeKigoIchiran                     G303_makeKigoIchiran
#define makeRkError                         G304_makeRkError
#define makeYomiReturnStruct                G305_makeYomiReturnStruct
#define mapFromHash                         G306_mapFromHash
#define mountnottry                         G307_mountnottry
#define moveStrings                         G308_moveStrings
#define moveToChikujiTanMode                G309_moveToChikujiTanMode
#define moveToChikujiYomiMode               G310_moveToChikujiYomiMode
#define multiSequenceFunc                   G311_multiSequenceFunc
#define nKouhoBunsetsu                      G312_nKouhoBunsetsu
#define newCoreContext                      G313_newCoreContext
#define newFilledYomiContext                G314_newFilledYomiContext
#define newIchiranContext                   G315_newIchiranContext
#define newYomiContext                      G316_newYomiContext
#define nkeysup                             G317_nkeysup
#define nothermodes                         G318_nothermodes
#define onoff_mode                          G319_onoff_mode
#define owcListCallback                     G320_owcListCallback
#define parse                               G321_parse
#define parse_string                        G322_parse_string
#define popCallback                         G323_popCallback
#define popForIchiranMode                   G324_popForIchiranMode
#define popMountMode                        G325_popMountMode
#define popTourokuMode                      G326_popTourokuMode
#define popYomiMode                         G327_popYomiMode
#define prepareHenkanMode                   G328_prepareHenkanMode
#define prevMenuIfExist                     G329_prevMenuIfExist
#define protocol_version                    G330_protocol_version
#define pushCallback                        G331_pushCallback
#define queryMode                           G332_queryMode
#define quickly_escape                      G333_quickly_escape
#define removeCurrentBunsetsu               G334_removeCurrentBunsetsu
#define removeKana                          G335_removeKana
#define resetModeNames                      G336_resetModeNames
#define restoreBindings                     G337_restoreBindings
#define restoreDefaultKeymaps               G338_restoreDefaultKeymaps
#define restoreFlags                        G339_restoreFlags
#define rkcWCinit                           G340_rkcWCinit
#define rkc_Connect_Iroha_Server            G341_rkc_Connect_Iroha_Server
#define rkc_get_dir_list                    G342_rkc_get_dir_list
#define rkc_get_kanji_list                  G343_rkc_get_kanji_list
#define rkcw_get_server_info                G344_rkcw_get_server_info
#define rmContext                           G345_rmContext
#define romaji_yuusen                       G346_romaji_yuusen
#define romajidic                           G347_romajidic
#define saveapname                          G348_saveapname
#define searchfunc                          G349_searchfunc
#define selectKeysup                        G350_selectKeysup
#define selectOnOff                         G351_selectOnOff
#define selectOne                           G352_selectOne
#define serverChange                        G353_serverChange
#define serverFin                           G354_serverFin
#define server_name                         G355_server_name
#define server_version                      G356_server_version
#define setMode                             G357_setMode
#define setWStrings                         G358_setWStrings
#define showmenu                            G359_showmenu
#define stayAfterValidate                   G360_stayAfterValidate
#define strokelimit                         G361_strokelimit
#define tanKouhoIchiran                     G362_tanKouhoIchiran
#define tanMuhenkan                         G363_tanMuhenkan
#define tankouho_mode                       G364_tankouho_mode
#define tourokureibun_mode                  G365_tourokureibun_mode
#define trimYomi                            G366_trimYomi
#define uiUtilIchiranTooSmall               G367_uiUtilIchiranTooSmall
//#define ushort2euc                          G368_ushort2euc
#define ushort2euc  G008_CNvW2E

#define ushort2eucsize                      G369_ushort2eucsize
#define ushort2wchar                        G370_ushort2wchar
#define ushortstrcpy                        G371_ushortstrcpy
//#define ushortstrlen                        G372_ushortstrlen
#define ushortstrlen  G128_WStrlen

#define ushortstrncpy                       G373_ushortstrncpy
#define uuKigoGeneralExitCatch              G374_uuKigoGeneralExitCatch
#define uuKigoMake                          G375_uuKigoMake
#define uuTTangoQuitCatch                   G376_uuTTangoQuitCatch
#define wchar2ushort                        G377_wchar2ushort
//#define wcharstrlen                         G378_wcharstrlen
#define wcharstrlen G128_WStrlen

#define wideproto                           G379_wideproto
#define xString                             G380_xString
#define yomiInfoLevel                       G381_yomiInfoLevel
#define yomi_mode                           G382_yomi_mode
#define doTanConvertTb                      G383_doTanConvertTb
#define doKakutei                           G384_doKakutei
#define restoreChikujiIfBaseChikuji         G385_restoreChikujiIfBaseChikuji
#define ReCheckStartp                       G386_ReCheckStartp
#define fitmarks                            G387_fitmarks
