.TH "canlisp" 1 "2003 Dec 20" "Debian" "canna"
.SH NAME
canlisp \- parse canlisp commands
.SH SYNOPSIS
.BI "canlisp [-cs " "cannaserver" "] [-f" " .canna-file" "]"
.SH DESCRIPTION
Processes canlisp commands.

.SH OPTIONS
.BI "-cs|-cannaserver " "cannaserver" ""
Connect to the cannaserver.

.BI "-f " ".canna"
Use 
.I ".canna"
for settings.

.SH NOTES

Canlisp is a language used for .canna files used in configuration for 
.B canna.

.SH "SEE ALSO"
.B "canlisp.tex documentation"

.SH AUTHOR
This manual page was written by Junichi Uekawa 
(dancer@debian.org) for Debian GNU/Linux and may be used by others.


