.TH "mergeword" 1 "2003 Dec 20" "Debian" "canna"
.SH NAME
mergeword \- merge words in canna dictionary files
.SH SYNOPSIS
.BI "mergeword [" "filename" "] " 
.SH DESCRIPTION
Reads text-based dictionary file from input and merge similar entries and output a dictionary file.
Reads from the specified filename, or from standard input if file is not specified.

.SH AUTHOR
This manual page was written by Junichi Uekawa 
(dancer@debian.org) for Debian GNU/Linux and may be used by others.
